# Enable or disable AI reviews globally
enabled: true

# Claude model to use (claude-sonnet-4-5-20250929, claude-opus-4-5-20251101)
model: claude-sonnet-4-5-20250929

# Maximum tokens for Claude's response
maxTokens: 4096

# Temperature for API calls (0.0 = deterministic, 1.0 = creative)
# Lower values produce more consistent severity ratings across runs
temperature: 0

# Review focus areas - toggle which aspects to review
reviewAreas:
  # Clean code, readability, maintainability
  codeQuality: true
  # Vulnerabilities, injection risks, data exposure
  security: true
  # Code comments, function docs
  documentation: true
  # Test coverage gaps, edge cases
  testCoverage: true
  # Language-specific best practices
  conventions: true

# Languages for specialized feedback
languages:
  - csharp
  - typescript
  - python

# File patterns to ignore (glob patterns) - files matching these won't be reviewed
ignorePatterns:
  - "*.lock"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "*.min.js"
  - "*.min.css"
  - "*.map"
  - "dist/**"
  - "build/**"
  - "out/**"
  - "node_modules/**"
  - ".git/**"
  - "*.generated.cs"
  - "*.Designer.cs"
  - "Migrations/**"

# Maximum characters per chunk - larger diffs are split into multiple API calls
chunkSize: 100000

# Maximum number of files to review per PR - prevents excessive API usage
maxFilesPerReview: 50

# Severity levels to include in the review - set false to hide that severity
severity:
  # Security issues, bugs causing failures
  critical: true
  # Potential bugs, performance issues
  warning: true
  # Improvements for maintainability
  suggestion: true
  # Minor style issues
  nitpick: false

# PR Size Warning - alerts when PRs exceed recommended size
prSizeWarning:
  # Enable PR size warnings
  enabled: true
  # Warn if total changed lines exceed this number
  maxLines: 1000
  # Warn if number of files exceed this number
  maxFiles: 30

# Review Caching - skip re-review if same commit was already reviewed
caching:
  # Enable review caching
  enabled: true

# Custom Review Instructions - parse <!-- ai-review: instructions --> from PR description
customInstructions:
  # Enable custom instructions parsing
  enabled: true

# Inline Ignore - skip specific lines/files with comments like // ai-review-ignore
inlineIgnore:
  # Enable inline ignore comments
  enabled: true
  # Patterns to detect ignore comments
  patterns:
    # Skip this specific line
    - "ai-review-ignore"
    # Skip the next line after this comment
    - "ai-review-ignore-next-line"
    # Skip the entire file
    - "ai-review-ignore-file"

# Metrics and Analytics - track review performance
metrics:
  # Enable metrics collection
  enabled: true
  # Show metrics in GitHub Actions summary
  showInSummary: true
  # Show metrics in PR review comment
  showInComment: true

# Feedback Loop - track emoji reactions on comments to measure effectiveness
feedbackLoop:
  # Enable feedback tracking
  enabled: true

# Contextual Awareness - read related files for more accurate reviews
contextualAwareness:
  # Enable contextual awareness
  enabled: true
  # Maximum number of related files to read
  maxRelatedFiles: 5
  # Include files that are imported/required by changed files
  includeImports: true
  # Include test files for the changed files
  includeTests: false
  # Include files with similar names
  includeSimilarFiles: false

# Auto-fix PRs - automatically create separate PRs with suggested fixes
autoFix:
  # Enable auto-fix (disabled by default for safety)
  enabled: true
  # Create fixes in a separate PR instead of committing to the same branch
  createSeparatePR: true
  # Require manual approval before creating the fix PR
  requireApproval: true
  # Branch name prefix for auto-fix branches
  branchPrefix: 'ai-fix/'

# Severity Threshold - filter comments by minimum severity
severityThreshold:
  # Enable severity filtering
  enabled: false
  # Minimum severity level to post comments (critical, warning, suggestion, nitpick)
  minSeverityToComment: 'warning'
  # Skip posting review entirely if no issues above threshold
  skipCleanPRs: false
