# AI PR Review Configuration
# This file allows you to customize the behavior of the AI PR review action.

# Enable or disable AI reviews globally
enabled: true

# Claude model to use for reviews
# Options: claude-sonnet-4-20250514, claude-opus-4-20250514
model: claude-sonnet-4-20250514

# Maximum tokens for Claude's response
maxTokens: 4096

# Review focus areas - disable any areas you don't want reviewed
reviewAreas:
  codeQuality: true      # Clean code, readability, maintainability
  security: true         # Vulnerabilities, injection risks, data exposure
  documentation: true    # Code comments, function docs
  testCoverage: true     # Test coverage gaps, edge cases
  conventions: true      # Language-specific best practices

# Languages to provide specialized feedback for
languages:
  - csharp
  - typescript
  - python

# File patterns to ignore (glob patterns)
# Files matching these patterns will not be reviewed
ignorePatterns:
  - "*.lock"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "*.min.js"
  - "*.min.css"
  - "*.map"
  - "dist/**"
  - "build/**"
  - "out/**"
  - "node_modules/**"
  - ".git/**"
  - "*.generated.cs"
  - "*.Designer.cs"
  - "Migrations/**"

# Maximum characters per chunk for large diffs
# Larger diffs will be split into multiple API calls
chunkSize: 100000

# Maximum number of files to review per PR
# Prevents excessive API usage on very large PRs
maxFilesPerReview: 50

# Severity levels to include in the review
# Set to false to hide comments of that severity
severity:
  critical: true    # Security issues, bugs causing failures
  warning: true     # Potential bugs, performance issues
  suggestion: true  # Improvements for maintainability
  nitpick: false    # Minor style issues (disabled by default)

# ============================================================================
# NEW FEATURES
# ============================================================================

# PR Size Warning - warn when PR is too large
prSizeWarning:
  enabled: true
  maxLines: 1000            # Warn if total changes exceed this
  maxFiles: 30              # Warn if number of files exceeds this

# Incremental Reviews - only review new commits after first review
incrementalReview:
  enabled: true
  # First review is always full, subsequent reviews are incremental

# Review Caching - skip re-review if commit already reviewed
caching:
  enabled: true

# Custom Review Instructions - parse PR description for focus areas
# Use <!-- ai-review: focus on security --> in PR description
customInstructions:
  enabled: true
  # Looks for: <!-- ai-review: your instructions here -->

# File-level ignore comments
# Add "// ai-review-ignore" or "# ai-review-ignore" to skip specific lines
inlineIgnore:
  enabled: true
  patterns:
    - "ai-review-ignore"
    - "ai-review-ignore-next-line"
    - "ai-review-ignore-file"

# Metrics and Analytics
metrics:
  enabled: true
  showInSummary: true       # Show in GitHub Actions summary
  showInComment: true       # Show in PR review comment
